### ISSUE TITLE
Release v0.10.5

### ISSUE THREAD

**Issue by ejfitzgerald** [fetchai/fetchd#249]
This issue tracks the progress for the v0.10.5 release for the `fetchd` ledger.

## Tasks

- [x] #247 
- [x] #246 
- [x] https://github.com/fetchai/cosmos-sdk/pull/131

## Release

- [x] Create release candidate
- [x] Test upgrade procedure on testnet
- [x] Create release version
- [x] Submit governance proposal for upgrade
