### ISSUE TITLE
Release v0.10.7

### ISSUE THREAD

**Issue by bryanchriswhite** [fetchai/fetchd#282]
## Summary

Tracking issue for the v0.10.7 (Eridanus) ledger release

## Outstanding Tasks

- fetchai/cosmos-sdk#133
- 
## Release

- [ ] Create intital betas
- [ ] Launch beta testnet
- [ ] Cut release candidate
- [ ] Upgrade testnet with release candidate
- [ ] Create final release
- [ ] Update testnet with production version
- [ ] Submit network upgrade proposal
